/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Builds {
  build_id: string;
  uploaded_at: number;
  version: string;
}

export interface CrashCounts {
  channel: string;
  count: Generated<number>;
  day: number;
  group_id: number;
  trust: number;
  version: string;
}

export interface CrashGroups {
  fault: string;
  fingerprint: string;
  first_seen: number;
  frames: string;
  id: Generated<number>;
  last_seen: number;
  message: string | null;
  sample_cap: number | null;
}

export interface CrashSamples {
  group_id: number;
  id: Generated<number>;
  r2_key: string;
  received_at: number;
  report_id: string;
  trust: number;
  version: string;
}

export interface Releases {
  channel: string;
  released_at: number;
  supported_until: number | null;
  version: string;
}

export interface Reports {
  channel: string;
  group_id: number;
  received_at: number;
  report_id: string;
  trust: number;
  user_key: string;
  version: string;
}

export interface Versions {
  created_at: number;
  version: string;
}

export interface DB {
  builds: Builds;
  crash_counts: CrashCounts;
  crash_groups: CrashGroups;
  crash_samples: CrashSamples;
  releases: Releases;
  reports: Reports;
  versions: Versions;
}
