/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Apps {
  created_at: number;
  created_by: string;
  disabled_at: number | null;
  display_name: string;
  id: Generated<number>;
  name: string;
}

export interface UploadTokens {
  app_id: number;
  created_at: number;
  created_by: string;
  hash: string;
  id: Generated<number>;
  label: string;
  last_used_at: number | null;
  revoked_at: number | null;
}

export interface DB {
  apps: Apps;
  upload_tokens: UploadTokens;
}
