/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Builds {
  build_id: string;
  uploaded_at: number;
  version: string;
}

export interface Releases {
  channel: string;
  released_at: number;
  supported_until: number | null;
  version: string;
}

export interface Versions {
  created_at: number;
  version: string;
}

export interface DB {
  builds: Builds;
  releases: Releases;
  versions: Versions;
}
