#!/bin/sh
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
. "$HERE/../env.sh"

"$HERE/build"
mkdir -p "$BUILD_DIR/test"
cd "$BUILD_DIR/test"
exec "$BUILD_DIR/msvc-wine-shims/wine-run" "$BIN_DIR/cw_test.exe" "$@"
